name: CI

on: [push, pull_request, release]

jobs:
  main:
    runs-on: ubuntu-20.04
    env:
      # webpack build needs a lot of memory
      NODE_OPTIONS: --max_old_space_size=4096

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          # Ensures all refs and tags are fetched so "git describe --always" is working as expected
          fetch-depth: 0

      # A workaround for annotated tags with actions/checkout@v2
      # see https://github.com/actions/checkout/issues/290
      - name: Fetch Tags correctly
        run: git fetch --force --tags

      - name: Cache gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/.cache/Cypress
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Run unit tests
        run: ./gradlew check jibDockerBuild -x bootJar

      - name: Run end-to-end tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: client
          install: false
          start: docker run -d -e CODEFREAK_REVERSE_PROXY_URL="http://$(docker network inspect bridge -f '{{ (index .IPAM.Config 0).Gateway }}')" -v /var/run/docker.sock:/var/run/docker.sock -p8080:8080 --name=cfreak-cypress cfreak/codefreak
          config-file: cypress/cypress-ci.json
          wait-on: 'http://localhost:8080'
          wait-on-timeout: 180
          headless: true
          record: true
          group: merge
          tag: ${{ github.event_name }}
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}

      - name: Prepare cache
        run: |
          rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
          rm -fr $HOME/.gradle/caches/*/plugin-resolution/

      - name: Before Deploy
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
        run: |
          pip3 install --upgrade pip
          pip3 install docker-ci-deploy
          docker logout
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

      - name: Deploy master branch as latest
        if: github.ref == 'refs/heads/master'
        run: python -m docker_ci_deploy --tag canary -- cfreak/codefreak

      # ${GITHUB_REF/refs\/tags\//} returns the tag name from 'refs/tags/TAG_NAME'
      - name: Deploy tags
        if: startsWith(github.ref, 'refs/tags')
        run: python -m docker_ci_deploy --version-latest --version ${GITHUB_REF/refs\/tags\//} --version-semver cfreak/codefreak
